stationGroupsTable <- stationGroups |>
  reactable::reactable(
    columns = list(
      group1 = reactable::colDef(
        name = "Group 1",
        #aggregate = NULL,
        #sortable = NULL,
        #resizable = NULL,
        #filterable = NULL,
        #searchable = NULL,
        #filterMethod = NULL,
        #show = TRUE,
        #defaultSortOrder = NULL,
        #sortNALast = FALSE,
        #format = NULL,
        #cell = NULL,
        #grouped = NULL,
        #aggregated = NULL,
        #header = NULL,
        #footer = NULL,
        #details = NULL,
        #filterInput = NULL,
        html = TRUE,
        na = "",
        rowHeader = TRUE,
        minWidth = 150,
        #maxWidth = NULL,
        #width = NULL,
        #align = NULL,
        #vAlign = NULL,
        #headerVAlign = NULL,
        #sticky = NULL,
        #class = NULL,
        #style = NULL,
        #headerClass = NULL,
        #headerStyle = NULL,
        #footerClass = NULL,
        #footerStyle = NULL
      ), 
      group2 = reactable::colDef(
        name = "Group 2",
        minWidth = 150,
        html = TRUE,
        na = "",
        rowHeader = TRUE
      ),
      group3 = reactable::colDef(
        name = "Group 3",
        minWidth = 150,
        html = TRUE,
        na = "",
        rowHeader = TRUE
      ),
      group4 = reactable::colDef(
        name = "Group 4",
        minWidth = 150,
        html = TRUE,
        na = "",
        rowHeader = TRUE
      ),
      group5 = reactable::colDef(
        name = "Group 5",
        minWidth = 150,
        html = TRUE,
        na = "",
        rowHeader = TRUE
      ),
      group6 = reactable::colDef(
        name = "Group 6",
        minWidth = 150,
        html = TRUE,
        na = "",
        rowHeader = TRUE
      )
    ),
    #columnGroups = NULL,
    rownames = FALSE,
    #groupBy = NULL,
    sortable = FALSE,
    resizable = FALSE,
    filterable = FALSE,
    searchable = FALSE,
    searchMethod = NULL,
    #defaultColDef = NULL,
    #defaultColGroup = NULL,
    #defaultSortOrder = "asc",
    #defaultSorted = NULL,
    pagination = FALSE,
    #defaultPageSize = 10,
    showPageSizeOptions = FALSE,
    #pageSizeOptions = c(10, 25, 50, 100),
    #paginationType = "numbers",
    showPagination = NULL,
    showPageInfo = FALSE,
    #minRows = 1,
    #paginateSubRows = FALSE,
    #details = NULL,
    defaultExpanded = TRUE,
    selection = NULL,
    defaultSelected = NULL,
    onClick = NULL,
    highlight = FALSE,
    outlined = FALSE,
    bordered = TRUE,
    #borderless = FALSE,
    striped = TRUE,
    compact = TRUE,
    #wrap = TRUE,
    #showSortIcon = TRUE,
    #showSortable = FALSE,
    #class = NULL,
    #style = NULL,
    #rowClass = NULL,
    #rowStyle = NULL,
    fullWidth = TRUE,
    width = "auto",
    height = "auto",
    theme = 
      reactable::reactableTheme(
        color = NULL,
        backgroundColor = NULL,
        borderColor = NULL,
        borderWidth = NULL,
        stripedColor = NULL,
        highlightColor = NULL,
        cellPadding = NULL,
        style = NULL,
        tableStyle = list(borderColor = "#CCCCCC"),
        headerStyle = 
          list(
            color = "#606060", 
            fontFamily = "monospace", 
            fontSize = "0.8rem",
            borderBottomColor = "#CCCCCC",
            borderBottomWidth = "1px"
          ),
        groupHeaderStyle = NULL,
        tableBodyStyle = NULL,
        rowGroupStyle = NULL,
        rowStyle = NULL,
        rowStripedStyle = NULL,
        rowHighlightStyle = NULL,
        rowSelectedStyle = NULL,
        cellStyle = list(color = "#606060", fontFamily = "monospace", fontSize = "0.8rem"),
        footerStyle = NULL,
        inputStyle = NULL,
        filterInputStyle = NULL,
        searchInputStyle = NULL,
        selectStyle = NULL,
        paginationStyle = NULL,
        pageButtonStyle = NULL,
        pageButtonHoverStyle = NULL,
        pageButtonActiveStyle = NULL,
        pageButtonCurrentStyle = NULL
      ),
    #language = getOption("reactable.language"),
    #meta = NULL,
    #elementId = NULL,
    #static = getOption("reactable.static", FALSE),
    #selectionId = NULL
  )
